export const EDITOR_TRAFFIC_LIGHT_POSITION = { x: 16, y: 16 } as const;
export const MACOS_TRAFFIC_LIGHT_CONTROL_GROUP_WIDTH = 68;
export const EDITOR_TRAFFIC_LIGHT_RESERVED_WIDTH =
  EDITOR_TRAFFIC_LIGHT_POSITION.x + MACOS_TRAFFIC_LIGHT_CONTROL_GROUP_WIDTH;
export const EDITOR_TITLEBAR_HEIGHT = 42;
